### ISSUE TITLE
Consider tagging repo with a sem ver tag

### ISSUE THREAD

**Issue by mfridman** [olekukonko/tablewriter#113]
Awesome package, thank you. Used it for a few projects. 

Would you consider tagging this project? (would play nice with others' go.mod)

**Comment by mattn** [comment]
ping @olekukonko

**Comment by olekukonko** [comment]
@mattn what do you think ?

**Comment by mattn** [comment]
I think we should tag it. `v0.0.1` ?

**Comment by olekukonko** [comment]
@mattn thanks for the Prompt response. I think you should go ahead and tag it

**Comment by mattn** [comment]
Okay, will do in later.

**Comment by mattn** [comment]
tagged v0.0.1
