### ISSUE TITLE
Make uppercase header formatting optional?

### ISSUE THREAD

**Issue by keronsen** [olekukonko/tablewriter#15]
Thank you for working on this library! It was really easy to set up and use.

I'm wondering if you have any thoughts on making the headers formatting optional? I'm working on a command line tool to display the contents of our data store on appstax.com, and as the column names are case sensitive, it's a bit misleading to show the headers in all caps.

Let me know what you think. I can take a look myself and send you a pull request if you'd like that.

**Comment by khaf** [comment]
:+1: I'm doing the same thing and had to change the code.

Formatting the column names is not a concern of the table writer.

I also have to thank you for this very useful and well designed library.

**Comment by olekukonko** [comment]
Send a Pull request ... something like `autoFormatTitle()` might work in order not to break existing code or what do you think ?

**Comment by khaf** [comment]
I feel like this can take part as a bit of a larger change, which is to let users customize some of the internal TableWriter settings like MAX_ROW_SIZE and others.

AutoFormatTitle can take a closure, and be called if not `nil`. Its default value could be a closure that does what it does now.

**Comment by olekukonko** [comment]
How is it different from https://github.com/olekukonko/tablewriter/pull/9 proposed by @juanmera

**Comment by keronsen** [comment]
@olekukonko I think `func (*Table) SetAutoFormatHeaders(bool)` would match the rest of the api well. I see that `Title(string)` is called in `SetHeader` and `SetFooter`. Maybe this should be moved to `printHeading` and `printFooter` so that `SetAutoFormatHeaders` can be called before or after `SetHeaders`?

**Comment by olekukonko** [comment]
@keronsen thanks for the contribution
