### ISSUE TITLE
No borders, when borders are disabled

### ISSUE THREAD

**Issue by crackcomm** [olekukonko/tablewriter#24]
Even if borders are disabled we get the space borders https://github.com/olekukonko/tablewriter/blob/master/table_test.go#L268

What would you recommend to actually disable the borders?
I was preparing to make a pull request but as seen in tests this type of table behavior would be unexpected.

My idea would be to `SetBorder(false)` make borders disappear and for space borders `SetBorderSeparator("  ")`?

**Comment by olekukonko** [comment]
How does this affect backward compatibility ?

**Comment by crackcomm** [comment]
Backwards compatibility was my main concern when I addressed this issue. Both issues in this case don't bother me as much so I am gonna let You decide whats better. I may apply a PR when You do.

**Comment by olekukonko** [comment]
I totally support cases where we need to make border disappear but here are my views

- A simple search on [table.SetBorder](https://github.com/search?l=&q=table.SetBorder+language%3AGo&ref=advsearch&type=Code&utf8=%E2%9C%93)  shows large usage of `table.SetBorder(false)` hence so may people are already expecting `SetBorderSeparator(" ")`  output 

- Rather then modification, It's possible to leave the behavior of `SetBorder(false)` then make our output work with `SetBorderSeparator("") ( empty Separator )` 

- The other option would be to add a new method or probably we should start looking at a flexible configuration mechanism eg.

```go

table := tablewriter.NewWriter(os.Stdout)
table.LoadConfig(config)

``` 

This would give us flexibility of different configuration .. and can even introduce style templates etc. 

What do you think  ?

**Comment by crackcomm** [comment]
At first glance I think the second point would look like a solution, if it's correct in total.

**Comment by olekukonko** [comment]
Cool ... second seems fine to me too ... you can send in your PR

**Comment by tfogo** [comment]
I'd also like to suggest that we have a way of removing the center separators on the border. E.g

```
  FIELD   |     TYPE     | NULL | KEY 
----------+--------------+------+-----
 user_id  | smallint(5)  | NO   | PRI 
 username | varchar(10)  | NO   |              
 password | varchar(100) | NO   |       
```

Currently, `SetBorder(false)` replaces the left/right borders with spaces, but the center separators on the borders remain:

```
   FIELD   |     TYPE     | NULL | KEY 
+----------+--------------+------+-----+
  user_id  | smallint(5)  | NO   | PRI 
  username | varchar(10)  | NO   |              
  password | varchar(100) | NO   |       
```

Perhaps a `SetCenterBorderSeparator` method would work? This would maintain backwards compatibility while providing this extra flexibility.

**Comment by JulienBreux** [comment]
```
table.SetBorder(false)
table.SetCenterSeparator("")
table.SetRowSeparator("")
table.SetColumnSeparator("")
```
