### ISSUE TITLE
Ansi modified strings break wrapping

### ISSUE THREAD

**Issue by neilmcgibbon** [olekukonko/tablewriter#27]
Firstly, this is an _awesome_ library, really really great.  

There seems to be a small bug when trying to wrap text with colourising modifications in the string (e.g. `\033[32m My string \033[00m`)

If I turn of Autowrap then things are fine, but if I keep it on, it wraps in really strange places. Looking at the Wrap utilities, they take into account `len(v)`  where `v` is the length of the string.  But in other places you use `DisplayWidth()` which takes into account an ANSI regex: 

`var ansi = regexp.MustCompile("\033\\[(?:[0-9]{1,3}(?:;[0-9]{1,3})*)?[m|K]")`

I'm not sure if its related, but just thought I'd point it out - I'm not using AutoWrap if I have string colouring.

Thanks, and again, great project!

**Comment by olekukonko** [comment]
i think we need to make wrap work with `ANSI regex` or better still have full color support ...

**Comment by mattn** [comment]
Now tablewriter have SetColumnColor. Please use it instead.
