### ISSUE TITLE
Flush

### ISSUE THREAD

**Issue by GoodWriteHQ** [olekukonko/tablewriter#28]
Wondering how I can stream a table to the console, instead of building the whole thing and calling `Render`...

**Comment by olekukonko** [comment]
It would be difficult to determine the `max` with of each column in data streaming. except a fixed width has been set from the beginning ...

**Comment by breerly** [comment]
That sounds like a reasonable constraint - perhaps set width and headers up front, then stream rows from there?

**Comment by FrenchBen** [comment]
Would it be possible to push each row to a buffer and then print it when 'ready'.

Something even like this would be helpful:
`output := table.Render()`

**Comment by breerly** [comment]
Possibly - but wouldn't that cause each row to have different widths?

**Comment by FrenchBen** [comment]
@breerly I'm unsure how the spacing is created.
I saw the title 'flush' and thought of the php `ob_flush` to flush the output buffer. Hence my comment about capturing the flushed output to a var.
