### ISSUE TITLE
The table is not formatted correctly when accented characters are used (UTF-8)

### ISSUE THREAD

**Issue by brunonova** [olekukonko/tablewriter#35]
This issue was spotted in [LXD](https://github.com/lxc/lxd/issues/2051), but isn't specific to it.

When fields in the table contain accented characters or other special characters, the table is not formatted correctly.
This is in a Linux terminal, with UTF-8.

Example result of an `lxc` command (in Portuguese):

```
$ lxc image list
+--------+--------------------+----------+-----------------------------------------------+--------+----------+------------------------------+
| ALIAS  | IMPRESSÃO DIGITAL | PÚBLICO |                  DESCRIÇÃO                  |  ARCH  | TAMANHO  |         UPLOAD DATE          |
+--------+--------------------+----------+-----------------------------------------------+--------+----------+------------------------------+
| xenial | d23ee1f4fd28       | não     | ubuntu 16.04 LTS amd64 (release) (20160516.1) | x86_64 | 138.85MB | May 26, 2016 at 8:04pm (UTC) |
+--------+--------------------+----------+-----------------------------------------------+--------+----------+------------------------------+
```

Notice that several `|` characters are not aligned.

Accented and special characters in UTF-8 span multiple chars/bytes.
You should take that into account when calculating the length of strings to display them (according to the `utf8` manpage, just count all chars whose most significant bits are not `10`).

**Comment by olekukonko** [comment]
I was thinking this has been fixed see https://github.com/olekukonko/tablewriter/pull/22/files
