### ISSUE TITLE
How about render a Struct directly

### ISSUE THREAD

**Issue by yittg** [olekukonko/tablewriter#42]
It would be really nice if I can render a Struct directly I think,
and I would be willing to implement it if needed

**Comment by olekukonko** [comment]
It would be difficult to implement that and still maintain compatibility ... Am also working on possible solutions

**Comment by yittg** [comment]
IMO, this is just a feature, not conflict with the core render mechanism.  Would you show more detail about compatibility. May reflect be a way to implement it. Also, a tag of fields can be provided.
More, may we can render a struct or slice of struct different way, like below:

|Field | Value|
|---|---|
|FieldA | hello|
|FieldB | world|

|  FieldA | FieldB |
|---|---|
| hello| world|
