### ISSUE TITLE
Feature request: clean up table

### ISSUE THREAD

**Issue by sitano** [olekukonko/tablewriter#45]
table.Clean() support

**Comment by olekukonko** [comment]
makes sense ... can you come up with a pull request ...

**Comment by zupzup** [comment]
I could do this.

Just a few questions:
* With "Clean" do you mean something like "Clear" which removes all the values from the table?
* If so, should just the values be removed, with the rows staying intact, or should all rows (lines) be removed?
* What about Header / Footer? Do they remain intact?

**Comment by ashmckenzie** [comment]
https://github.com/olekukonko/tablewriter/pull/66 for you perusal :)
