### ISSUE TITLE
ANSI colours

### ISSUE THREAD

**Issue by endofunky** [olekukonko/tablewriter#48]
Using ANSI colour codes in the header strings appears to mess up, i assume, the width calculations. Colour codes in the border strings and row columns appears to be fine.

**Comment by hasit** [comment]
@endofunky 

Can you add way to reproduce the error? Maybe add a screenshot along with it so we can look at whats going wrong.

**Comment by lunixbochs** [comment]
You could use vtclean to process/strip escape sequences to more accurately calculate string widths: https://github.com/lunixbochs/vtclean

Example:

    len(vtclean.Clean(str, false))

**Comment by liyu4** [comment]
![image](https://cloud.githubusercontent.com/assets/5621417/22676013/f48af2ee-ed23-11e6-8635-7ef2a0d12262.png)

**Comment by mattn** [comment]
It's possible with github.com/mattn/go-colorable. But ANSI color is strings of escape sequences. And it should be skipped as zero width letters. Current implementation of tablewriter doesn't skip those escape sequences.

**Comment by liyu4** [comment]
yeap，maybe i will commit pr

**Comment by lunixbochs** [comment]
You could use https://github.com/lunixbochs/vtclean to strip escapes for width calculation.

**Comment by mattn** [comment]
if you want Writer, go-colorable have NoColorable.

**Comment by olekukonko** [comment]
@mattn it will be nice if you give him some examples on how to combine both libraries

**Comment by mattn** [comment]
Closed by https://github.com/olekukonko/tablewriter/pull/50, https://github.com/olekukonko/tablewriter/pull/70
