### ISSUE TITLE
Contributors Needed

### ISSUE THREAD

**Issue by olekukonko** [olekukonko/tablewriter#51]
Hello,

Have been busy with so many projects lately and don't have time to update this project. I will appreciate if dedicated like minds who understand and use this lib can offer their assistance. 

Thanks
Oleku

**Comment by mattn** [comment]
I'm okay to do. Do you hope to keep this repository in same go import-path? Or move this into organization?

**Comment by zupzup** [comment]
Hey, 

I'd be happy to help. :)

I didn't find a contribution guideline or anything, so should I just grab an issue, comment that I'm working on it and then do it? Or is there a specific way you want to handle this?

**Comment by olekukonko** [comment]
@mattn @zupzup ..  One month is more than enough time to wait for contributors. Thanks for indicating your Intrest in this project. 

Why goals for this project is simple 

- Default table writer for command line applications 
- It must be very simple and easy to use
- No complex configurations 
- Modelled after the std lib 
- Improve Speed
- 

@mattn I don't want any breaking changes yet until we have detailed specs for possible tablewriter 2 then we can move. For now, we should maintain `same go import-path`

@zupzup That is why I needed help :) 


Once again .. welcome guys
