### ISSUE TITLE
feature request: an alternative to Append which does not trim spaces

### ISSUE THREAD

**Issue by knz** [olekukonko/tablewriter#52]
If a value inserted in a table contains spaces at the beginning or at the end this is currently stripped by `Append`. This is inconvenient if the client app is trying to use white space to show something useful, for example indentation in source code with one line per row.

To address this there should be a flag to `Append` or a new API `AppendRaw` which does not trim the argument.

**Comment by olekukonko** [comment]
Makes sense ... This gives a lot of flexibility ...  would you like to send in a pull request  ?
