### ISSUE TITLE
Is this abandonware?

### ISSUE THREAD

**Issue by jaytaylor** [olekukonko/tablewriter#69]
It'd be helpful to understand why tablewriter PR's don't seem to get much love.

If olekukonko isn't able to (or interested in?) maintain this package it'd be helpful to know so other plans can be made.

Thank you,
Jay

**Comment by olekukonko** [comment]
Hello Jay,

Nope, This is actively used and maintained.  Have been busy lately but I intend to upgrade and work on an improved version very soon. 

Your PR is welcome (If it's backward compatible)  and contributors are welcome too. 

Regards
Oleku

**Comment by jaytaylor** [comment]
Thanks.
