### ISSUE TITLE
csv output

### ISSUE THREAD

**Issue by avasseur-pivotal** [olekukonko/tablewriter#80]
Is there a way to write csv as output file ?

**Comment by olekukonko** [comment]
You can write to any `io.writer` 

```
table := tablewriter.NewWriter(csv-file-writer)

```

**Comment by greut** [comment]
@avasseur-pivotal https://golang.org/pkg/encoding/csv/

**Comment by displague** [comment]
This fails:
```
var _ io.Writer = (*csv.Writer)(nil)
```

It seems `csv.NewWriter(os.Stdout)` does not implement `io.Writer`. It writes strings instead of the needed bytes.
